# Generated by Django 4.1.13 on 2024-03-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='confirmpassword',
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='phonenumber',
            field=models.CharField(max_length=20),
        ),
    ]
